'use strict';
// 根据参考成品照片重建；步骤由本站推导。
const REFERENCE_MODELS = [
 {
  id:"ref-turtle",
  name:"弧背小乌龟",
  level:"big",
  category:"animals",
  collection:"reference",
  reference:"https://www.xiaohongshu.com/explore/691ae30c000000001b031425",
  subtitle:"原造型参考 · 弧背小乌龟",
  concept:"locking",
  steps:[
   {"title":"摆好四只脚","text":"前后两排，各摆两块绿色方砖。两只脚之间留一块方砖的空隙。","pieces":[{"x":1,"y":0,"w":1,"c":"green","z":1},{"x":3,"y":0,"w":1,"c":"green","z":1},{"x":1,"y":0,"w":1,"c":"green"},{"x":3,"y":0,"w":1,"c":"green"}]},
   {"title":"连起身体","text":"每排用两块绿色长砖连接两只脚。最左边比前脚伸出一列凸点。","pieces":[{"x":0.5,"y":1,"w":2,"c":"green","z":1},{"x":2.5,"y":1,"w":2,"c":"green","z":1},{"x":0.5,"y":1,"w":2,"c":"green"},{"x":2.5,"y":1,"w":2,"c":"green"}]},
   {"title":"搭弧形龟壳","text":"前后两排都使用两块弧形砖：左侧高端朝右，右侧高端朝左。弯曲边朝外。","pieces":[{"x":1,"y":2,"w":1.5,"c":"green","z":1,"kind":"curve","flip":true},{"x":2.5,"y":2,"w":1.5,"c":"green","z":1,"kind":"curve"},{"x":1,"y":2,"w":1.5,"c":"green","kind":"curve","flip":true},{"x":2.5,"y":2,"w":1.5,"c":"green","kind":"curve"}]},
   {"title":"扣住龟壳中间","text":"绿色长砖长边朝前后，跨住两边弧形砖的平顶凸点。","pieces":[{"x":2,"y":3,"w":1,"c":"green","d":2}]},
   {"title":"加脑袋和尾巴","text":"黄色眼睛方砖做脑袋，绿色弧形砖做尾巴。尾巴高端朝左。","pieces":[{"x":0,"y":2,"w":1,"c":"yellow","kind":"eye"},{"x":4,"y":2,"w":1.5,"c":"green","kind":"curve"}]},
  ],
  ideas:["看看乌龟的前后两排脚。", "给乌龟搭一个小池塘。", "找找弧形龟壳上真正有凸点的位置。"]
 },
 {
  id:"ref-elephant",
  name:"蓝色小象",
  level:"big",
  category:"animals",
  collection:"reference",
  reference:"https://www.xiaohongshu.com/explore/691ae30c000000001b031425",
  subtitle:"原造型参考 · 蓝色小象",
  concept:"locking",
  steps:[
   {"title":"摆好四条腿","text":"前后两排各摆两块蓝色方砖，中间留一个方砖宽的空隙。","pieces":[{"x":1,"y":0,"w":1,"c":"blue","z":1},{"x":3,"y":0,"w":1,"c":"blue","z":1},{"x":1,"y":0,"w":1,"c":"blue"},{"x":3,"y":0,"w":1,"c":"blue"}]},
   {"title":"搭长鼻子底部","text":"前面的左侧摆蓝色方砖，作为向下伸的鼻子。","pieces":[{"x":0,"y":0,"w":1,"c":"blue"}]},
   {"title":"连接腿和鼻子","text":"前排最左长砖连接鼻子和左腿。身体用蓝色长砖和方砖搭起。","pieces":[{"x":0,"y":1,"w":2,"c":"blue"},{"x":2,"y":1,"w":2,"c":"blue"},{"x":1,"y":1,"w":2,"c":"blue","z":1},{"x":3,"y":1,"w":1,"c":"blue","z":1}]},
   {"title":"加眼睛和耳朵","text":"前面左侧加蓝色眼睛方砖，旁边黄色方砖表示耳朵；后排也搭起身体。","pieces":[{"x":0,"y":2,"w":1,"c":"blue","kind":"eye"},{"x":1,"y":2,"w":1,"c":"yellow"},{"x":2,"y":2,"w":2,"c":"blue"},{"x":1,"y":2,"w":1,"c":"yellow","z":1},{"x":2,"y":2,"w":2,"c":"blue","z":1}]},
   {"title":"搭圆圆的背","text":"两排弧形砖的高端都朝中间。","pieces":[{"x":1,"y":3,"w":1.5,"c":"blue","z":1,"kind":"curve","flip":true},{"x":2.5,"y":3,"w":1.5,"c":"blue","z":1,"kind":"curve"},{"x":1,"y":3,"w":1.5,"c":"blue","kind":"curve","flip":true},{"x":2.5,"y":3,"w":1.5,"c":"blue","kind":"curve"}]},
   {"title":"连接前后身体","text":"长砖长边朝前后，扣在两侧弧形砖的平顶上。","pieces":[{"x":2,"y":4,"w":1,"c":"blue","d":2}]},
  ],
  ideas:["把鼻子颜色换成灰色。", "和大象雕塑放在一起，比较大小。", "找找连接前后两排身体的那块长砖。"]
 },
 {
  id:"ref-snail",
  name:"橙壳小蜗牛",
  level:"big",
  category:"animals",
  collection:"reference",
  reference:"https://www.xiaohongshu.com/explore/691ae30c000000001b031425",
  subtitle:"原造型参考 · 橙壳小蜗牛",
  concept:"locking",
  steps:[
   {"title":"摆长长的身体","text":"两块蓝色长砖紧挨着。","pieces":[{"x":0,"y":0,"w":2,"c":"blue"},{"x":2,"y":0,"w":2,"c":"blue"}]},
   {"title":"搭脖子和弧形壳","text":"左边立起蓝色方砖；橙色弧形砖高端朝中间，其中左边一块要跨过底座接缝。","pieces":[{"x":0,"y":1,"w":1,"c":"blue"},{"x":1,"y":1,"w":1.5,"c":"orange","kind":"curve","flip":true},{"x":2.5,"y":1,"w":1.5,"c":"orange","kind":"curve"}]},
   {"title":"把壳连起来","text":"橙色方砖跨住两块弧形砖的平顶。","pieces":[{"x":2,"y":2,"w":1,"c":"orange"}]},
   {"title":"搭头和眼睛","text":"蓝色弧形砖高端朝左，扣住脖子；眼睛砖只扣在平顶的凸点上。","pieces":[{"x":0,"y":2,"w":1.5,"c":"blue","kind":"curve"},{"x":0,"y":3,"w":1,"c":"blue","kind":"eye"}]},
  ],
  ideas:["给蜗牛安排一条慢慢爬的小路。", "换一换壳的颜色。", "摸摸弧面和平顶，哪里可以继续接积木？"]
 },
 {
  id:"ref-cat",
  name:"尖耳小猫",
  level:"big",
  category:"animals",
  collection:"reference",
  reference:"https://www.xiaohongshu.com/explore/691ae30c000000001b031425",
  subtitle:"原造型参考 · 尖耳小猫",
  concept:"balance",
  steps:[
   {"title":"摆两只脚","text":"两块黄色方砖之间留一列凸点的间隙。","pieces":[{"x":0.5,"y":0,"w":1,"c":"yellow"},{"x":2,"y":0,"w":1,"c":"yellow"}]},
   {"title":"连接身体","text":"红色长砖同时扣住两只脚，黄色长砖叠在上面。","pieces":[{"x":0.5,"y":1,"w":2,"c":"red"},{"x":0.5,"y":2,"w":2,"c":"yellow"}]},
   {"title":"搭脖子和脑袋","text":"脖子居中，红色长砖做脸的底部。","pieces":[{"x":1,"y":3,"w":1,"c":"yellow"},{"x":0.5,"y":4,"w":2,"c":"red"}]},
   {"title":"加两只眼睛","text":"两块眼睛方砖左右紧挨着。","pieces":[{"x":0.5,"y":5,"w":1,"c":"yellow","kind":"eye"},{"x":1.5,"y":5,"w":1,"c":"yellow","kind":"eye"}]},
   {"title":"装尖耳朵","text":"左耳高端朝左，右耳高端朝右，弧边向中间落下。","pieces":[{"x":0,"y":6,"w":1.5,"c":"red","kind":"curve"},{"x":1.5,"y":6,"w":1.5,"c":"red","kind":"curve","flip":true}]},
   {"title":"搭卷尾巴","text":"尾巴下部扣在右脚上，弧形砖高端朝右。","pieces":[{"x":2.5,"y":1,"w":1,"c":"red"},{"x":2.5,"y":2,"w":1.5,"c":"yellow","kind":"curve","flip":true}]},
  ],
  ideas:["给小猫起名字。", "用不同颜色做两只耳朵。", "扶住底部，看看头放在哪个位置比较稳。"]
 },
 {
  id:"ref-swan",
  name:"红色弯颈天鹅",
  level:"big",
  category:"animals",
  collection:"reference",
  reference:"https://www.xiaohongshu.com/explore/691ae30c000000001b031425",
  subtitle:"原造型参考 · 红色弯颈天鹅",
  concept:"balance",
  steps:[
   {"title":"摆底座","text":"红色长砖做天鹅的落脚处。","pieces":[{"x":1,"y":0,"w":2,"c":"red"}]},
   {"title":"搭身体和翘尾","text":"两块弧形砖相邻，身体高端朝左，尾巴高端朝右。","pieces":[{"x":1,"y":1,"w":1.5,"c":"red","kind":"curve"},{"x":2.5,"y":1,"w":1.5,"c":"red","kind":"curve","flip":true}]},
   {"title":"搭长脖子","text":"两块红色方砖往上叠。","pieces":[{"x":1,"y":2,"w":1,"c":"red"},{"x":1,"y":3,"w":1,"c":"red"}]},
   {"title":"搭弯弯的嘴和脑袋","text":"黄色弧形砖高端朝右；眼睛砖扣在右侧平顶上。","pieces":[{"x":0,"y":4,"w":1.5,"c":"yellow","kind":"curve","flip":true},{"x":0.5,"y":5,"w":1,"c":"red","kind":"eye"}]},
  ],
  ideas:["和小鸭放在一起，比较脖子长短。", "给天鹅围一片湖水。", "扶住底座，再轻轻按紧长脖子。"]
 },
 {
  id:"ref-crocodile",
  name:"张嘴小鳄鱼",
  level:"big",
  category:"animals",
  collection:"reference",
  reference:"https://www.xiaohongshu.com/explore/691ae30c000000001b031425",
  subtitle:"原造型参考 · 张嘴小鳄鱼",
  concept:"locking",
  steps:[
   {"title":"摆前后脚","text":"两块绿色方砖之间留一个方砖宽的空隙。","pieces":[{"x":1,"y":0,"w":1,"c":"green"},{"x":3,"y":0,"w":1,"c":"green"}]},
   {"title":"搭长身体","text":"两块绿色长砖同时扣在脚上。左边伸出的部分是下嘴。","pieces":[{"x":0,"y":1,"w":2,"c":"green"},{"x":2,"y":1,"w":2,"c":"green"}]},
   {"title":"跨接身体和尾巴","text":"黄色长砖跨过绿色身体的接缝；尾巴弧形砖高端朝左。","pieces":[{"x":1,"y":2,"w":2,"c":"yellow"},{"x":3,"y":2,"w":1.5,"c":"green","kind":"curve"}]},
   {"title":"搭上嘴","text":"绿色长砖左端伸出，右半扣住黄色长砖，中间留下张嘴的空隙。","pieces":[{"x":0,"y":3,"w":2,"c":"green"}]},
   {"title":"加眼睛","text":"眼睛方砖扣在上嘴中间偏左。","pieces":[{"x":0.5,"y":4,"w":1,"c":"yellow","kind":"eye"}]},
  ],
  ideas:["看看上嘴和下嘴之间的空隙。", "搭一座河岸让鳄鱼休息。", "哪块砖把两段身体连在一起？"]
 },
 {
  id:"ref-crab",
  name:"大钳子螃蟹",
  level:"big",
  category:"animals",
  collection:"reference",
  reference:"https://www.xiaohongshu.com/explore/691ae30c000000001b031425",
  subtitle:"原造型参考 · 大钳子螃蟹",
  concept:"locking",
  steps:[
   {"title":"摆脚和钳子底座","text":"中间黄色长砖，左右两块黄色长砖做钳子底座。","pieces":[{"x":1,"y":0,"w":2,"c":"orange"},{"x":-1,"y":0,"w":2,"c":"orange"},{"x":3,"y":0,"w":2,"c":"orange"}]},
   {"title":"连接身体与钳子","text":"两块红色长砖扣在黄色底座上，分别连接左、中、右；两端再加黄色方砖。","pieces":[{"x":0,"y":1,"w":2,"c":"red"},{"x":2,"y":1,"w":2,"c":"red"},{"x":-1,"y":1,"w":1,"c":"orange"},{"x":4,"y":1,"w":1,"c":"orange"}]},
   {"title":"加眼睛和弧形大钳子","text":"眼睛长砖跨过身体接缝。左右钳子高端朝中间。","pieces":[{"x":1,"y":2,"w":2,"c":"red","kind":"eye"},{"x":-1,"y":2,"w":1.5,"c":"orange","kind":"curve","flip":true},{"x":3.5,"y":2,"w":1.5,"c":"orange","kind":"curve"}]},
  ],
  ideas:["给螃蟹搭一片沙滩。", "左右钳子像照镜子，找找对应的位置。", "中间哪块长砖连接了左右身体？"]
 },
 {
  id:"ref-flower",
  name:"弧瓣小红花",
  level:"big",
  category:"plants",
  collection:"reference",
  reference:"https://www.xiaohongshu.com/explore/6822f51f000000000303c1ad",
  subtitle:"原造型参考 · 弧瓣小红花",
  concept:"symmetry",
  steps:[
   {"title":"搭花盆和茎","text":"底座居中，把绿色方砖往上叠。","pieces":[{"x":1,"y":0,"w":2,"c":"green"},{"x":1.5,"y":1,"w":1,"c":"green"},{"x":1.5,"y":2,"w":1,"c":"green"}]},
   {"title":"添一片弯弯的叶子","text":"绿色弧形砖高端朝左，扣在底座右端。","pieces":[{"x":2.5,"y":1,"w":1.5,"c":"green","kind":"curve"}]},
   {"title":"搭花朵下半部","text":"红色长砖横放在茎上，再逐步向两边展开。","pieces":[{"x":1,"y":3,"w":2,"c":"red"},{"x":0.5,"y":4,"w":2,"c":"red"},{"x":2.5,"y":4,"w":1,"c":"red"}]},
   {"title":"搭花心和左右花瓣","text":"黄色长砖跨过下层接缝，两侧各加一块红色方砖。","pieces":[{"x":1,"y":5,"w":2,"c":"yellow"},{"x":0,"y":5,"w":1,"c":"red"},{"x":3,"y":5,"w":1,"c":"red"}]},
   {"title":"搭弧形花瓣","text":"左右弧形砖高端朝中间，用红色长砖连接上面的平顶。","pieces":[{"x":0.5,"y":6,"w":1.5,"c":"red","kind":"curve","flip":true},{"x":2,"y":6,"w":1.5,"c":"red","kind":"curve"},{"x":1,"y":7,"w":2,"c":"red"}]},
  ],
  ideas:["把红花变成蓝花。", "再搭一朵不同高度的花。", "找找左右对称的花瓣。"]
 },
 {
  id:"ref-apple",
  name:"圆润小苹果",
  level:"big",
  category:"plants",
  collection:"reference",
  reference:"https://www.xiaohongshu.com/explore/6822f51f000000000303c1ad",
  subtitle:"原造型参考 · 圆润小苹果",
  concept:"symmetry",
  steps:[
   {"title":"搭苹果底部","text":"红色长砖居中，上一层向两边展开。","pieces":[{"x":1,"y":0,"w":2,"c":"red"},{"x":0.5,"y":1,"w":2,"c":"red"},{"x":2.5,"y":1,"w":1,"c":"red"}]},
   {"title":"搭弧形果身","text":"左右两块红色弧形砖高端朝中间，中间填一块方砖。","pieces":[{"x":0,"y":2,"w":1.5,"c":"red","kind":"curve","flip":true},{"x":1.5,"y":2,"w":1,"c":"red"},{"x":2.5,"y":2,"w":1.5,"c":"red","kind":"curve"}]},
   {"title":"连接上半部","text":"红色长砖跨接果身中间的三块砖。","pieces":[{"x":1,"y":3,"w":2,"c":"red"}]},
   {"title":"加果梗和叶子","text":"绿色方砖做果梗，弧形砖高端朝左，弯边朝右。","pieces":[{"x":1.5,"y":4,"w":1,"c":"green"},{"x":1.5,"y":5,"w":1.5,"c":"green","kind":"curve"}]},
  ],
  ideas:["用黄色搭一个黄苹果。", "旁边再搭一个小花篮。", "左右弧形砖的高端为什么朝中间？"]
 },
 {
  id:"ref-house",
  name:"弧顶窗户小屋",
  level:"big",
  category:"buildings",
  collection:"reference",
  reference:"https://www.xiaohongshu.com/explore/6822f51f000000000303c1ad",
  subtitle:"原造型参考 · 弧顶窗户小屋",
  concept:"support",
  steps:[
   {"title":"铺好地基","text":"两块绿色长砖左右紧挨着。","pieces":[{"x":0,"y":0,"w":2,"c":"green"},{"x":2,"y":0,"w":2,"c":"green"}]},
   {"title":"安装窗框和两侧墙","text":"红色窗框居中，它有两块普通砖的高度；左右各叠两块方砖。","pieces":[{"x":1,"y":1,"w":2,"c":"red","kind":"window"},{"x":0,"y":1,"w":1,"c":"yellow"},{"x":3,"y":1,"w":1,"c":"yellow"},{"x":0,"y":2,"w":1,"c":"green"},{"x":3,"y":2,"w":1,"c":"green"}]},
   {"title":"搭弧形屋顶","text":"左边弧形砖高端朝右，右边高端朝左，中间绿色方砖补齐。","pieces":[{"x":0,"y":3,"w":1.5,"c":"green","kind":"curve","flip":true},{"x":1.5,"y":3,"w":1,"c":"green"},{"x":2.5,"y":3,"w":1.5,"c":"green","kind":"curve"}]},
   {"title":"连接屋顶并加烟囱","text":"黄色长砖扣住屋顶三块砖的平顶，蓝色方砖做烟囱。","pieces":[{"x":1,"y":4,"w":2,"c":"yellow"},{"x":2,"y":5,"w":1,"c":"blue"}]},
  ],
  ideas:["窗户里住着谁？", "给小屋搭一条小路。", "屋顶两头靠哪里支撑？"]
 },
 {
  id:"ref-bus",
  name:"双层巴士",
  level:"big",
  category:"vehicles",
  collection:"reference",
  reference:"https://www.xiaohongshu.com/explore/691ae3480000000004012a08",
  subtitle:"原造型参考 · 双层巴士",
  concept:"support",
  steps:[
   {"title":"准备轮轴底盘","text":"使用带轮子的2×6底盘。轮子已经装在底盘上。","pieces":[{"x":0,"y":0,"w":3,"c":"red","kind":"wheelbase"}]},
   {"title":"铺底层地板","text":"蓝色长砖和方砖铺满底盘。","pieces":[{"x":0,"y":1,"w":2,"c":"blue"},{"x":2,"y":1,"w":1,"c":"blue"}]},
   {"title":"搭第一层车窗","text":"红色窗框有两块普通砖高；右侧叠两块黄色方砖。","pieces":[{"x":0,"y":2,"w":2,"c":"red","kind":"window"},{"x":2,"y":2,"w":1,"c":"yellow"},{"x":2,"y":3,"w":1,"c":"yellow"}]},
   {"title":"连接楼层","text":"绿色长砖跨住窗框与后墙，右端补一块绿色方砖。","pieces":[{"x":0.5,"y":4,"w":2,"c":"green"},{"x":2.5,"y":4,"w":1,"c":"green"}]},
   {"title":"搭第二层车窗","text":"第二个窗框放在绿色地板上，后墙再叠两块黄色方砖。","pieces":[{"x":0.5,"y":5,"w":2,"c":"red","kind":"window"},{"x":2.5,"y":5,"w":1,"c":"yellow"},{"x":2.5,"y":6,"w":1,"c":"yellow"}]},
   {"title":"搭圆弧车顶","text":"两块黄色弧形砖高端朝中间，用红色长砖连接上方凸点。","pieces":[{"x":0,"y":7,"w":1.5,"c":"yellow","kind":"curve","flip":true},{"x":1.5,"y":7,"w":1.5,"c":"yellow","kind":"curve"},{"x":0.5,"y":8,"w":2,"c":"red"}]},
  ],
  ideas:["巴士开往什么地方？", "给它搭一座站台。", "楼层长砖跨住了窗框和哪面墙？"]
 },
 {
  id:"ref-excavator",
  name:"弧斗挖掘机",
  level:"big",
  category:"vehicles",
  collection:"reference",
  reference:"https://www.xiaohongshu.com/explore/691ae3480000000004012a08",
  subtitle:"原造型参考 · 弧斗挖掘机",
  concept:"support",
  steps:[
   {"title":"准备底盘和铲斗底座","text":"右边使用2×6轮轴底盘；左边黄色长砖作为铲斗的底部。","pieces":[{"x":1,"y":0,"w":3,"c":"red","kind":"wheelbase"},{"x":-1,"y":0,"w":2,"c":"yellow"}]},
   {"title":"搭车身和铲斗","text":"蓝色长砖与黄色方砖铺在底盘上。铲斗弧形砖高端朝左，旁边黄色方砖做机械臂下端。","pieces":[{"x":1,"y":1,"w":2,"c":"blue"},{"x":3,"y":1,"w":1,"c":"yellow"},{"x":-1.5,"y":1,"w":1.5,"c":"yellow","kind":"curve"},{"x":0,"y":1,"w":1,"c":"yellow"}]},
   {"title":"搭驾驶室与机械臂","text":"绿色窗框有两块普通砖高；机械臂左侧叠两块黄色方砖。","pieces":[{"x":2,"y":2,"w":2,"c":"green","kind":"window"},{"x":0,"y":2,"w":1,"c":"yellow"},{"x":0,"y":3,"w":1,"c":"yellow"}]},
   {"title":"跨接机械臂和驾驶室","text":"两块黄色长砖左右并排，一头在机械臂上，一头在驾驶室上。再用长砖跨过接缝，形成固定造型。","pieces":[{"x":0,"y":4,"w":2,"c":"yellow"},{"x":2,"y":4,"w":2,"c":"yellow"},{"x":1,"y":5,"w":2,"c":"yellow"}]},
  ],
  ideas:["铲斗里要装什么？", "给挖掘机搭一个工地。", "这是固定机械臂，先扶好两头，再按紧顶部跨接砖。"]
 },
];
